export const CampaignActionTypes = {
    CREATE_CAMPAIGN: 'CREATE_CAMPAIGN',
    DELETE_CAMPAIGN: 'DELETE_CAMPAIGN',
    GET_CAMPAIGN: 'GET_CAMPAIGNS',
    EDIT_CAMPAIGN: 'EDIT_CAMPAIGN',
    GO_TO_PAGE: 'GO_TO_PAGE'
}