export const UserActionTypes = {
    LOGIN_USER: 'LOGIN_USER',
    LOGOUT_USER: 'LOGOUT_USER',
    USER_LOADING: 'USER_LOADING',
    UPDATE_PROFILE: 'UPDATE_PROFILE',
    SET_CURRENT_USER: 'SET_CURRENT_USER'
}